In [2]:
import pandas as pd
import numpy as np

# series

In [3]:
s = pd.Series([0,1,1,2,3,5,8])

In [4]:
s

0    0
1    1
2    1
3    2
4    3
5    5
6    8
dtype: int64

In [6]:
type(s)

pandas.core.series.Series

In [7]:
s = pd.Series([0.0,1,1,2,3,5,8])

In [8]:
s.values

array([0., 1., 1., 2., 3., 5., 8.])

In [9]:
type(s.values)

numpy.ndarray

In [10]:
s.index

RangeIndex(start=0, stop=7, step=1)

In [11]:
for v in s.values:
  print(v)

0.0
1.0
1.0
2.0
3.0
5.0
8.0


In [12]:
for i in s.index:
  print(i)

0
1
2
3
4
5
6


In [13]:
for item in zip(s.index, s.values):
  print(item, type(item))

(0, 0.0) <class 'tuple'>
(1, 1.0) <class 'tuple'>
(2, 1.0) <class 'tuple'>
(3, 2.0) <class 'tuple'>
(4, 3.0) <class 'tuple'>
(5, 5.0) <class 'tuple'>
(6, 8.0) <class 'tuple'>


In [14]:
s[5]

5.0

In [15]:
s[3]

2.0

In [16]:
pd.Series([0.33, 57.9, 4222.6])

0       0.33
1      57.90
2    4222.60
dtype: float64

# mass, diameter, dayLength

In [17]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [18]:
mercury["Mass"]

0.33

In [19]:
mercury["DayLength"]

4222.6

In [20]:
arr = np.random.randint(0, 10, 10)

In [21]:
arr

array([9, 4, 4, 6, 8, 4, 4, 4, 0, 3])

In [22]:
rand_series = pd.Series(arr)
rand_series

0    9
1    4
2    4
3    6
4    8
5    4
6    4
7    4
8    0
9    3
dtype: int32

# iLoc and Loc

In [24]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [25]:
mercury["Mass"]

0.33

In [26]:
mercury[0]

0.33

In [27]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=[1, 2, 3])

In [28]:
mercury[0]

KeyError: 0

In [29]:
mercury[1]

0.33

In [30]:
mercury.loc[1]

0.33

In [31]:
mercury.iloc[1]

57.9

In [32]:
#  0 1 2 3 4 5   -> implicit indexing(iLoc)
#  2 3 4 5 6 7   -> explicit indexing(Loc)
# [1 2 3 4 5 6]

In [33]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [34]:
mercury.loc["Mass":"Diameter"]

Mass         0.33
Diameter    57.90
dtype: float64

In [35]:
mercury.loc["Mass":]

Mass            0.33
Diameter       57.90
DayLength    4222.60
dtype: float64

In [36]:
mercury.loc[:]

Mass            0.33
Diameter       57.90
DayLength    4222.60
dtype: float64

In [37]:
mercury.loc[::-1]

DayLength    4222.60
Diameter       57.90
Mass            0.33
dtype: float64

In [38]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=[1, 2, 3])

In [39]:
mercury.loc[1:2]

1     0.33
2    57.90
dtype: float64

In [40]:
mercury.iloc

In [41]:
mercury = pd.Series([0.33, 57.9, 4222.6], index=["Mass", "Diameter", "DayLength"])

In [42]:
mercury.iloc[0]

0.33

In [43]:
mercury.iloc[2]

4222.6

In [44]:
mercury.loc["Mass"]

0.33

In [45]:
mercury.loc["DayLength"]

4222.6

# Nifty Case Study

In [46]:
import pandas as pd 
import numpy as np

In [47]:
nifty = pd.read_csv('nifty.csv', index_col=0).iloc[:, 0]

In [48]:
nifty_df = pd.read_csv('nifty.csv')
type(nifty_df)

pandas.core.frame.DataFrame

In [49]:
nifty

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
                 ...   
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, Length: 245, dtype: float64

In [50]:
nifty.head()

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
Name: Close, dtype: float64

In [51]:
nifty.head(10)

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
08-Jan-2019    10802.15
09-Jan-2019    10855.15
10-Jan-2019    10821.60
11-Jan-2019    10794.95
14-Jan-2019    10737.60
Name: Close, dtype: float64

In [52]:
nifty.tail()

Date
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, dtype: float64

In [53]:
nifty.tail(10)

Date
17-Dec-2019    12165.00
18-Dec-2019    12221.65
19-Dec-2019    12259.70
20-Dec-2019    12271.80
23-Dec-2019    12262.75
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, dtype: float64

In [54]:
np.mean(nifty)

11432.632244897959

In [55]:
type(nifty)

pandas.core.series.Series

In [56]:
np.median(nifty)

11512.4

# Question: How many days did the markets close higher than the previous day's close.

In [57]:
nifty[0]

10910.1

In [58]:
nifty[1]

10792.5

In [59]:
nifty[1] - nifty[0]

-117.60000000000036

In [60]:
nifty[1:]

Date
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
08-Jan-2019    10802.15
                 ...   
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
31-Dec-2019    12168.45
Name: Close, Length: 244, dtype: float64

In [61]:
nifty[:-1]

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
                 ...   
23-Dec-2019    12262.75
24-Dec-2019    12214.55
26-Dec-2019    12126.55
27-Dec-2019    12245.80
30-Dec-2019    12255.85
Name: Close, Length: 244, dtype: float64

In [62]:
nifty[1:] - nifty[:-1]

Date
01-Apr-2019    0.0
01-Aug-2019    0.0
01-Feb-2019    0.0
01-Jan-2019    NaN
01-Jul-2019    0.0
              ... 
31-Dec-2019    NaN
31-Jan-2019    0.0
31-Jul-2019    0.0
31-May-2019    0.0
31-Oct-2019    0.0
Name: Close, Length: 245, dtype: float64

In [63]:
nifty.values[1:] - nifty.values[:-1]

array([-1.1760e+02, -1.2025e+02,  5.5100e+01,  4.4450e+01,  3.0350e+01,
        5.3000e+01, -3.3550e+01, -2.6650e+01, -5.7350e+01,  1.4920e+02,
        3.5000e+00,  1.4900e+01,  1.7500e+00,  5.4900e+01, -3.9100e+01,
       -9.1250e+01,  1.8300e+01, -6.9250e+01, -1.1900e+02, -9.3500e+00,
       -4.0000e-01,  1.7915e+02,  6.2700e+01,  1.8600e+01,  2.2100e+01,
        1.2810e+02,  6.9500e+00, -1.2580e+02, -5.4800e+01, -5.7400e+01,
       -3.7750e+01, -4.7600e+01, -2.1650e+01, -8.3450e+01, -3.6600e+01,
        1.3110e+02,  5.4400e+01,  1.8000e+00,  8.8450e+01, -4.4800e+01,
       -2.8650e+01, -1.4150e+01,  7.1000e+01,  1.2395e+02,  6.5550e+01,
        5.2000e+00, -2.2800e+01,  1.3265e+02,  1.3315e+02,  4.0500e+01,
        1.5500e+00,  8.3600e+01,  3.5350e+01,  7.0200e+01, -1.1350e+01,
       -6.4150e+01, -1.0265e+02,  1.2900e+02, -3.8200e+01,  1.2495e+02,
        5.3900e+01,  4.5250e+01,  4.4050e+01, -6.9250e+01, -4.5950e+01,
        6.7950e+01, -6.1450e+01,  6.7450e+01, -8.7650e+01,  1.24

In [64]:
(nifty.values[1:] - nifty.values[:-1]) > 0

array([False, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True, False,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False, False,

In [65]:
np.sum((nifty.values[1:] - nifty.values[:-1]) > 0)

129