In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.random.randint(0, 10, (5, 3))
arr

array([[8, 5, 2],
       [8, 3, 2],
       [0, 1, 9],
       [8, 0, 2],
       [8, 7, 8]])

In [3]:
df = pd.DataFrame(arr)
df

0  1  2
0  8  5  2
1  8  3  2
2  0  1  9
3  8  0  2
4  8  7  8

In [4]:
df.values

array([[8, 5, 2],
       [8, 3, 2],
       [0, 1, 9],
       [8, 0, 2],
       [8, 7, 8]])

In [5]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [7]:
for c in df.columns:
  print(c)

0
1
2


In [8]:
df.values[1]

array([8, 3, 2])

In [9]:
df.index = ["R1", "R2", "R3", "R4", "R5"]
df.columns = ["C1", "C2", "C3"]

In [14]:
df

C1  C2  C3
R1   8   5   2
R2   8   3   2
R3   0   1   9
R4   8   0   2
R5   8   7   8

In [11]:
df.loc["R3", "C2"]

1

In [13]:
df.iloc[1, 1]

3

In [15]:
df.iloc[2,1]

1

In [16]:
temp_df = df.iloc[2:4, 1:3]

In [17]:
temp_df

C2  C3
R3   1   9
R4   0   2

In [18]:
type(temp_df)

pandas.core.frame.DataFrame

In [19]:
df.iloc[0]

C1    8
C2    5
C3    2
Name: R1, dtype: int32

In [20]:
type(df.iloc[0])

pandas.core.series.Series

In [21]:
df.iloc[:, 0]

R1    8
R2    8
R3    0
R4    8
R5    8
Name: C1, dtype: int32

In [22]:
def create_df(nRows, nCols, maxRand=10):
  arr = np.random.randint(0, maxRand, (nRows, nCols))
  df = pd.DataFrame(arr)
  
  df.index = ['R' + str(x) for x in np.arange(1, nRows+1)]
  df.columns = ['C' + str(x) for x in np.arange(1, nCols+1)]

  return df

In [23]:
create_df(5, 3)

C1  C2  C3
R1   3   2   2
R2   4   6   6
R3   3   8   2
R4   7   6   9
R5   5   8   0

In [24]:
create_df(2, 5)

C1  C2  C3  C4  C5
R1   5   6   8   9   6
R2   6   4   7   5   1