In [1]:
import numpy as np


In [2]:
# 2-D Array
arr2d = np.array([
                  [1, 2, 3],
                  [4, 5, 6]
])

In [3]:
arr2d1 = np.array([[1,2,3],[4,5,6]])

In [4]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2d1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2d.ndim

2

In [7]:
arr2d.shape

(2, 3)

In [8]:
arr2d.size

6

In [9]:
# 3-D Array
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10, 11, 12]
                  ]
                ])

In [10]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d.ndim

3

In [13]:
arr3d.shape

(2, 2, 3)

In [14]:
arr3d.size

12

# Numpy Operations

In [15]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
120 * np.ones((2, 3))

array([[120., 120., 120.],
       [120., 120., 120.]])

In [19]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# Random
np.random.randn(2, 3)

array([[ 2.2340798 , -0.65797029, -1.59548759],
       [-0.40973134, -0.11394332,  0.2642347 ]])

In [21]:
np.random.rand(2, 3)

array([[0.13211329, 0.74802074, 0.23572311],
       [0.84763904, 0.24205437, 0.56197172]])

In [22]:
np.random.randint(0, 100, (2, 3))

array([[90, 39, 64],
       [27, 44, 55]])

In [23]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [25]:
str_arr = np.array(['1.1', '2.2', '3.3', '4.4'])

In [26]:
str_arr

array(['1.1', '2.2', '3.3', '4.4'], dtype='<U3')

In [28]:
# conversion
arr = np.array(str_arr, dtype='float')

In [29]:
arr

array([1.1, 2.2, 3.3, 4.4])

In [30]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)

In [31]:
arr1

array([[0.88843235, 0.16804904, 0.86047824, 0.10047101],
       [0.16199775, 0.83708219, 0.4020534 , 0.4103548 ],
       [0.62301541, 0.69290011, 0.68018372, 0.16842281]])

In [32]:
arr2

array([[0.99138072, 0.75958414, 0.12066322, 0.98127403],
       [0.955106  , 0.75563826, 0.31910722, 0.7437128 ],
       [0.41037384, 0.19852219, 0.44818762, 0.80358728]])

In [33]:
arr1 + arr2

array([[1.87981307, 0.92763318, 0.98114146, 1.08174504],
       [1.11710375, 1.59272045, 0.72116062, 1.1540676 ],
       [1.03338925, 0.8914223 , 1.12837135, 0.97201009]])

In [34]:
arr1 - arr2

array([[-0.10294837, -0.5915351 ,  0.73981501, -0.88080301],
       [-0.79310825,  0.08144392,  0.08294618, -0.333358  ],
       [ 0.21264157,  0.49437791,  0.2319961 , -0.63516446]])

In [35]:
arr1 * arr2

array([[0.88077471, 0.12764739, 0.10382808, 0.0985896 ],
       [0.15472502, 0.63253133, 0.12829814, 0.30518612],
       [0.25566923, 0.13755605, 0.30484993, 0.13534243]])

In [36]:
arr1 / arr2

array([[0.89615657, 0.22123822, 7.13123858, 0.10238834],
       [0.16961233, 1.10778163, 1.259932  , 0.55176514],
       [1.51816551, 3.4902904 , 1.51763165, 0.2095887 ]])

In [37]:
np.exp(arr1)

array([[2.43131521, 1.18299462, 2.36429112, 1.10569159],
       [1.1758576 , 2.3096181 , 1.49489115, 1.50735249],
       [1.86454193, 1.99950592, 1.97424041, 1.18343688]])

In [38]:
np.exp?

In [39]:
np.log(arr1)

array([[-0.11829677, -1.78349943, -0.15026695, -2.29788601],
       [-1.82017283, -0.17783302, -0.91117037, -0.89073314],
       [-0.47318403, -0.36686943, -0.38539234, -1.78127771]])

In [40]:
np.log(np.exp(arr1))

array([[0.88843235, 0.16804904, 0.86047824, 0.10047101],
       [0.16199775, 0.83708219, 0.4020534 , 0.4103548 ],
       [0.62301541, 0.69290011, 0.68018372, 0.16842281]])

In [41]:
print(np.log(np.exp(arr1)))

[[0.88843235 0.16804904 0.86047824 0.10047101]
 [0.16199775 0.83708219 0.4020534  0.4103548 ]
 [0.62301541 0.69290011 0.68018372 0.16842281]]


In [42]:
np.sqrt(arr1)

array([[0.94256689, 0.40993785, 0.92761966, 0.31697163],
       [0.40248944, 0.91492196, 0.63407681, 0.64058941],
       [0.78931325, 0.83240622, 0.82473252, 0.41039349]])

# cric_data

In [44]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)


In [47]:
cric_data.shape

(225, 4)

# Question 1: Find the mean, median for Sachin, Rahul, India

In [48]:
cric_data = cric_data[:, [1, 2, 3]]

In [49]:
cric_data.shape

(225, 3)

In [50]:
sachin = cric_data[:, 0]
rahul = cric_data[:, 1]
india = cric_data[:, 2]

In [52]:
sachin.shape

(225,)

In [53]:
def stats(col):
  print('Mean', np.mean(col))
  print('Median', np.median(col))

In [54]:
stats(sachin)

Mean 39.87555555555556
Median 27.0


In [55]:
stats(rahul)

Mean 32.062222222222225
Median 22.0


In [60]:
stats(india)

Mean 220.79555555555555
Median 216.0


In [61]:
np.mean(cric_data, axis=0)

array([ 39.87555556,  32.06222222, 220.79555556])

# Question 2: Find histogram of Sachin's scores with 10 bins

In [62]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

# Question 3: find mean of sachin's scores grouped by 25 matches

In [63]:
sachin.shape

(225,)

In [64]:
sachin25 = sachin.reshape(9, 25)

In [65]:
np.mean(sachin25, axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

# Question 4: Find mean of Sachin's scores where he has scored a century

In [66]:
sachin >= 100

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [67]:
sachin[sachin >= 100]

array([100., 104., 138., 141., 186., 146., 141., 123., 120., 122., 100.,
       152., 105., 122., 100., 117., 141., 139., 114., 127., 110., 146.,
       101., 140., 113., 102.])

In [68]:
np.mean(sachin[sachin >= 100])

125.0

# Question 5: Find mean of Sachin's scores when Rahul has scored less than 10

In [69]:
rahul <= 10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
        True, False,  True, False,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
       False, False, False, False, False, False, False,  True,  True,
       False, False,  True, False,  True, False, False, False, False,
        True,  True,  True, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True, False, False, False, False,  True, False, False, False,
        True, False,

In [70]:
sachin[rahul <= 10]

array([ 37.,  14.,   4.,   0.,  62.,  38.,  65.,   0.,  48.,  62.,  27.,
        27.,  51.,  18.,  65.,  28.,   2.,  54.,   4.,  14., 100.,  57.,
         0.,   5.,   0.,  30.,  83.,  93.,   0., 152.,   0.,   1.,  53.,
         0.,  81.,  78., 122.,   9.,  13.,  36.,  29.,  12.,  34., 100.,
        44.,  82.,   0.,   6.,  49.,  64.,  43.,  72.,   3.,  44.,  47.,
        17.,  35.,  88.,   0.,  33., 110., 146.,   7.,  11.,  94.,  55.,
         0.,  28.,   2.,  27.,  40.])

In [72]:
np.mean(sachin[rahul <= 10])

40.2112676056338